#!/bin/bash

while true
do
	displays=$(xrandr --current | grep -Ev "disconnected" | grep -B 1 "*" | awk '{print $1}' | sed 1q)
	mem_array=($(free -m | grep Mem | awk '{print $4; print $7}'))
	print_date=$(date '+%a-%d-%m-%T');
	cpu=$(top -bn1 | grep load | awk '{printf "%.2f%%", $(NF-2)}');
	cpu_temp=$(head -c 2 /sys/class/thermal/thermal_zone0/temp);
	network=$(iw wlp2s0 link | grep SSID | sed 's,.*SSID: ,,');
	disk_usage=$(df -h | awk '$NF=="/"{printf "%s", $5}');
networkicon="${network}|"
mail_count=$(find ~/.local/share/mail/*/INBOX/new/ -type f | wc -l)
mail_count_icon=""


if [[ $mail_count == "0" ]]
then
	mail_count_icon=""
fi
if [[ $mail_count -gt 0 ]]
then
mail_count_icon="[$mail_count]|"
fi


battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
if [[ ! $battery_level -gt '10' ]]
then 
	battery_low="!|";
fi
if [[ ! $battery_level -lt '20' ]]
then
	battery_low="|";
fi
#checks if AC cable is plugged in

ac_connected=$(cat /sys/class/power_supply/*/online)

if [ "$ac_connected" == '1' ]
then
	charging="[~]"
fi

if [ "$ac_connected" == '0' ]
then
	charging=""
fi
battery_icon=""
if [[ ${displays} == "HDMI-2" ]]
then
	networkicon=""
	charging=""
	if [[ ! "${mem_array[0]}" -lt "300" ]]
	then
		mem_icon=""
	fi
	if [[ "${mem_array[0]}" -lt "300" ]]
	then
		mem_icon="${mem_array[0]}MB/${mem_array[1]}MB|"
	fi
	if [[ "$battery_level" -lt "100" ]]
	then
		battery_icon="$battery_level%|"
	fi
	if [[ ! "$battery_level" -lt "100" ]]
	then
		battery_icon=""
	fi
	battery_low=""
	battery_level=""
fi
if [[ ${displays} == "LVDS1" ]]
then
	networkicon="${network}|"
	mem_icon="${mem_array[0]}MB/${mem_array[1]}MB|"
	battery_icon="$battery_level%"

fi








string=$(echo -e "${mem_icon}$mail_count_icon${networkicon}${battery_icon}${battery_level}${charging}${battery_low}${print_date}" );

xsetroot -bg pink -fg cyan -name "${string}";
sleep 1
done;
