#!/bin/bash
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

chosen=$(grep -v "#" ~/.config/emoji | dmenu -i -l 20)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard

# s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$c" | tr -d '\n' | xclip &
