#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
	*mkv|*webm|*mp4|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*)
		setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source*)
		setsid tsp curl -LO "$1" >/dev/null 2>&1 & ;;
	*)
		if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
		else
			link_check=$(echo "$1" | grep -q "https://imgur.com/a/")
			if [[ "${link_check}" -eq 0 ]]
			then
			album_name=$(echo "$1" | awk -F "/" '{print $5}')
			mkdir /tmp/${album_name}
			~/.scripts/imguralbum.py "$1" /tmp/${album_name} >/dev/null 2>&1
			sxiv -a /tmp/${album_name}/* >/dev/null 2>&1 &
		fi
	fi

		#else setsid "$BROWSER" "$1" >/dev/null 2>&1 & fi ;;
esac
